[package]
name = "sleep"
version = "0.1.0"
authors = ["GrayJack <gr41.j4ck@gmail.com>"]
build = "build.rs"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "^2.33.0", features = ["yaml", "wrap_help"] }
sugars = "^1.0.0"

[build-dependencies]
clap = { version = "^2.33.0", features = ["yaml"] }
