language: rust
rust:
  - 1.39.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - name: "Miri Check"
      rust: nightly
      before_script:
        - rustup component add miri
      script:
        - cargo miri test -j16 --verbose
    - name: "Check formatting"
      rust: nightly # Nightly because some of the settings are unstable; not "nightly" to avoid the allow_failures check!
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt -- --check
cache: cargo
before_script:
  - rustup target add x86_64-unknown-netbsd x86_64-unknown-freebsd
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo check --verbose --all --target x86_64-unknown-freebsd
  # - cargo check --verbose --all --target x86_64-unknown-netbsd
