status = [
    "Linux (1.46.0)",
    "Linux (stable)",
    "MacOS (1.46.0)",
    "MacOS (stable)",
    "FreeBSD (1.46.0)",
    "FreeBSD (stable)",
    "NetBSD (1.46.0)",
    "NetBSD (stable)",
    "Illumos (1.47.0)",
    "Illumos (stable)",
    "Solaris (1.46.0)",
    "Solaris (stable)",
    "Fuchsia (1.46.0)",
    "Fuchsia (stable)",
    "Format",
]
delete_merged_branches = true
