status = [
    "linux (ubuntu-latest, 1.43.0)",
    "linux (ubuntu-latest, stable)",
    "macos (macOS-latest, 1.43.0)",
    "macos (macOS-latest, stable)",
    "freebsd (ubuntu-latest, 1.43.0)",
    "freebsd (ubuntu-latest, stable)",
    "netbsd (ubuntu-latest, 1.43.0)",
    "netbsd (ubuntu-latest, stable)",
    "solaris (ubuntu-latest, 1.43.0)",
    "solaris (ubuntu-latest, stable)",
    "fuchsia (ubuntu-latest, 1.43.0)",
    "fuchsia (ubuntu-latest, stable)",
    "format (ubuntu-latest, nightly)",
]
delete_merged_branches = true