[package]
name = "unlink"
version = "0.1.0"
authors = ["Torbjörn Lönnemark <tobbez@ryara.net>"]
build = "build.rs"
edition = "2018"
description = "Call the unlink function to remove a specified FILE."

[dependencies]
clap = { version = "^2.33.0", features = ["wrap_help"] }

[build-dependencies]
clap = "^2.33.0"
