[package]
name = "link"
version = "0.1.0"
authors = ["Torbjörn Lönnemark <tobbez@ryara.net>"]
build = "build.rs"
edition = "2018"
description = "Creates a (hard) link to a file."

[dependencies]
clap = { version = "^2.33.0", features = ["wrap_help"] }

[build-dependencies]
clap = "^2.33.0"
