[package]
name = "rmdir"
version = "0.1.0"
authors = ["silverweed <silverweed1991@gmail.com>", "GrayJack <gr41.j4ck@gmail.com>"]
build = "build.rs"
edition = "2018"
description = "Remove empty directories."

[dependencies]
clap = { version = "^2.33.0", features = ["wrap_help"] }

[build-dependencies]
clap = "^2.33.0"
