[package]
name = "nl"
version = "0.0.0"
authors = ["Bojan Durdevic <bojan88@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
clap = { version = "^2.33.0", features = ["yaml", "wrap_help"] }
regex = "^1.3.1"

[build-dependencies]
clap = { version = "^2.33.0", features = ["yaml"] }
