[package]
name = "my-tool"
version = "0.1.0"
authors = ["Author <email@email.com>"]
description = "Tool description (required)"
build = "build.rs"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33.0"

[build-dependencies]
clap = "^2.33.0"
