[package]
name = "date"
version = "0.1.0"
authors = ["Jonas Geschke <mail@yonny.de>"]
build = "build.rs"
edition = "2018"

[dependencies]
clap = { version = "^2.33.0", features = ["yaml", "wrap_help"] }
chrono = { version = "~0.4", features = ["serde"] }
libc =  { version = "~0.2.65", features = ["extra_traits"] }
errno = "~0.2.4"
chrono-tz = "~0.5"

[build-dependencies]
clap = { version = "^2.33.0", features = ["yaml"] }
chrono = { version = "~0.4", features = ["serde"] }
libc =  { version = "~0.2.65", features = ["extra_traits"] }
errno = "~0.2.4"
chrono-tz = "~0.5"
