name: DragonflyBSD

on: [push]

jobs:
  check:
    name: DragonflyBSD
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [nightly]
        # rust: [1.46.0, stable]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
        components: rust-src
        # target: x86_64-unknown-dragonfly
    - name: Setup TOML
      run: cp DragonflyBSD.toml Cargo.toml
    - name: Check DragonflyBSD
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --target x86_64-unknown-dragonfly -Z build-std
