name: Fuchsia

on: [push, pull_request]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [1.39.0, stable]
    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Install target
      run: rustup target add x86_64-fuchsia aarch64-fuchsia
    - name: Setup TOML
      run: cp Fuchsia.toml Cargo.toml
    - name: Check Fuchsia (x86_64)
      run: cargo check --verbose --target x86_64-fuchsia
    - name: Check Fuchsia (aarch64)
      run: cargo check --verbose --target aarch64-fuchsia
