name: Fuchsia

on: [push, pull_request]

jobs:
  check:
    name: fuchsia
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [1.43.0, stable]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
        components: clippy
        target: x86_64-fuchsia
    - name: Add more targets
      run: rustup target add aarch64-fuchsia
    - name: Setup TOML
      run: cp Fuchsia.toml Cargo.toml
    - name: Check Fuchsia (x86_64)
      run: cargo check --verbose --target x86_64-fuchsia
    - name: Check Fuchsia (aarch64)
      run: cargo check --verbose --target aarch64-fuchsia
