name: Haiku

on: [push]

jobs:
  check:
    name: Haiku
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.46.0, stable]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
        target: x86_64-unknown-haiku
    - name: Setup TOML
      run: cp Haiku.toml Cargo.toml
    - name: Check Haiku
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --target x86_64-unknown-haiku
