name: Haiku

on: [push]

jobs:
  check:
    name: haiku
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [1.46.0, stable]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
        components: clippy
        target: x86_64-unknown-haiku
    - name: Check Haiku
      run: |
        cp Haiku.toml Cargo.toml
        cargo check --verbose --target x86_64-unknown-haiku
