name: Linux

on: [push, pull_request]

jobs:
  build:
    name: linux
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [1.46.0, stable, beta, nightly]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
        components: clippy
        target: aarch64-unknown-linux-gnu
    - name: Add more targets
      run: rustup target add i686-unknown-linux-gnu
    - name: Setup TOML
      run: cp Linux.toml Cargo.toml
    - name: Check Linux (x86_64 GNU)
      run: cargo check --verbose
    # - name: Check Linux (x86_64 MUSL)
    #   run: cargo check --verbose --target x86_64-unknown-linux-musl
    - name: Check Linux (i686 GNU)
      run: cargo check --verbose --target i686-unknown-linux-gnu
    # - name: Check Linux (i686 MUSL)
    #   run: cargo check --verbose --target i686-unknown-linux-musl
    - name: Check Linux (aarch64 GNU)
      run: cargo check --verbose --target aarch64-unknown-linux-gnu
    # - name: Check Linux (aarch64 MUSL)
    #   run: cargo check --verbose --target aarch64-unknown-linux-musl
    - name: Run tests
      run: cargo test --verbose
