name: MacOS

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        rust: [1.40.0, stable, beta, nightly]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
        components: clippy
    - name: Setup TOML
      run: cp MacOS.toml Cargo.toml
    - name: Check MacOS (x86_64)
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
