name: NetBSD

on: [push, pull_request]

jobs:
  check:
    name: netbsd
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [1.43.0, stable]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
        components: clippy
        target: x86_64-unknown-netbsd
    - name: Check NetBSD
      run: |
        cp NetBSD.toml Cargo.toml
        cargo check --verbose --target x86_64-unknown-netbsd
