name: OpenBSD

on: [push]

jobs:
  build:
    name: OpenBSD
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # rust: [1.46.0, stable]
        rust: [nightly]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
        # profile: minimal
        components: rust-src
    - name: Setup TOML
      run: cp OpenBSD.toml Cargo.toml
    - name: Check OpenBSD
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --target x86_64-unknown-openbsd -Z build-std
