name: OpenBSD

on: [push]

jobs:
  build:
    name: openbsd
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [1.45.0, stable]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
        components: clippy
        target: x86_64-unknown-openbsd
    - name: Check OpenBSD --target x86_64-unknown-openbsd
      run: |
        cp OpenBSD.toml Cargo.toml
        cargo check --verbose
