name: Solaris

on: [push, pull_request]

jobs:
  build:
    name: solaris
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [1.46.0, stable]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
        components: clippy
        target: x86_64-sun-solaris
    - name: Check Solaris
      run: |
        cp Solaris.toml Cargo.toml
        cargo check --verbose --target x86_64-sun-solaris
